create_candidate:
    locales:
        en: "/register"
        fr: "/inscription"
    defaults: { _controller: ClientBundle:Client:create }
edit_candidate:
    locales:
        en: "/edit"
        fr: "/editer"
    defaults: { _controller: ClientBundle:Client:edit }
delete_candidate:
    locales:
        en: "/delete"
        fr: "/supprimer"
    defaults: { _controller: ClientBundle:Client:delete }
show_candidate:
    locales:
        en: "/{id}"
        fr: "/{id}"
    requirements:
      id: \d+
    defaults: { _controller: ClientBundle:Client:show }
dashboard_candidate:
    locales:
        en: "/dashboard"
        fr: "/tableau-de-bord"
    defaults: { _controller: ClientBundle:Client:dashboard }
search_candidate:
    locales:
        en: "/search"
        fr: "/chercher"
    defaults: { _controller: ClientBundle:Client:search }
erase_ununsed_cvs:
    locales:
        en: "/erase-unused-cvs"
        fr: "/supprimer-cv-inutile"
    defaults: { _controller: ClientBundle:Client:eraseUnusedCvs }