dashboard_admin:
    locales:
        en: "/dashboard"
        fr: "/tableau-de-bord"
    defaults: { _controller: AdminBundle:Admin:index }

list_employer_admin:
    locales:
        en: "/employer/list"
        fr: "/employeur/liste"
    defaults: { _controller: AdminBundle:Admin:listPro }

list_candidate_admin:
    locales:
        en: "/candidate/list"
        fr: "/candidat/liste"
    defaults: { _controller: AdminBundle:Admin:listClient }

add_credit_admin:
    locales:
        en: "/add-credit"
        fr: "/ajouter-credit"
    defaults: { _controller: AdminBundle:Admin:addCredit }

list_admin:
    locales:
        en: "/admin/list"
        fr: "/admin/liste"
    defaults: { _controller: AdminBundle:Admin:listAdmin }

remove_admin:
    locales:
        en: "/remove-admin"
        fr: "/supprimer-admin"
    defaults: { _controller: AdminBundle:Admin:removeFromAdmin }

promote_admin:
    locales:
        en: "/promote-to--admin"
        fr: "/ajouter-admin"
    defaults: { _controller: AdminBundle:Admin:promoteToAdmin }

list_offer_admin:
    locales:
        en: "/offer/list"
        fr: "/offre/liste"
    defaults: { _controller: AdminBundle:Admin:listOffer }

change_validation_status:
    locales:
        en: "/change-validation-status"
        fr: "/changer-status-validation"
    defaults: { _controller: AdminBundle:Admin:changeValidationStatus }

log_page:
    locales:
        en: "/log-page"
        fr: "/page-stat"
    defaults: { _controller: AdminBundle:Admin:logPage }

list_ad_admin:
    locales:
        en: "/ad/list/{archived}"
        fr: "/pub/liste/{archived}"
    defaults: { _controller: AdminBundle:Ad:listAd }

create_ad:
    locales:
        en: "/ad/create"
        fr: "/pub/creation"
    defaults: { _controller: AdminBundle:Ad:create }

edit_ad:
    locales:
        en: "/ad/edit"
        fr: "/pub/edition"
    defaults: { _controller: AdminBundle:Ad:edit }
archive_ad:
    locales:
        en: "/ad/archive"
        fr: "/pub/archiver"
    defaults: { _controller: AdminBundle:Ad:archive }