<?php

namespace AppBundle\Repository;

/**
 * AdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCurrentAds()
    {
        $query = $this->createQueryBuilder('a');
        $query->andWhere('a.archived = 0 and (a.startDate <= CURRENT_TIMESTAMP() and a.endDate >= CURRENT_TIMESTAMP())');

        $ads = $query->getQuery()->getResult();

        return $ads;
    }
}
