<?php

namespace AppBundle\Repository;

/**
 * ContractTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
