<?php

namespace AppBundle\Repository;

/**
 * FeaturedOfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeaturedOfferRepository extends \Doctrine\ORM\EntityRepository
{

    public function getCurrentFeaturedOffer()
    {

        $query = $this->createQueryBuilder('fo')->select("fo")
            ->leftJoin('AppBundle:offer', 'o', 'WITH', 'o = fo.offer');
        $query->andWhere('o.archived = 0 AND fo.archived = 0 AND fo.startDate <= CURRENT_TIMESTAMP() AND fo.endDate > CURRENT_TIMESTAMP()');


        $offers = $query->getQuery()->getResult();

        return $offers;
    }

}
