<?php

namespace AppBundle\Repository;

/**
 * FeaturedProRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeaturedProRepository extends \Doctrine\ORM\EntityRepository
{

    public function getCurrentFeaturedPro()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT fe FROM AppBundle:featuredPro fe WHERE fe.archived = 0 AND  fe.startDate < CURRENT_TIMESTAMP() AND fe.endDate > CURRENT_TIMESTAMP()'
            )->execute();
    }

}
