<?php

namespace AppBundle\Repository;

/**
 * logCreditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogCreditRepository extends \Doctrine\ORM\EntityRepository
{
}
