<?php

namespace AppBundle\Repository;

/**
 * logCreditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogCreditRepository extends \Doctrine\ORM\EntityRepository
{

    public function countTotalBefore($date){
        return $this->getEntityManager()
            ->createQuery(
                'select sum(lc.credit) as total
                    from AppBundle:logCredit lc
                    where lc.date <= :date'
            )->setParameter('date',$date)->execute();
    }

}
