<?php

namespace AppBundle\Repository;

/**
 * OfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferRepository extends \Doctrine\ORM\EntityRepository
{
    public function boostOffer($employerId)
    {
        return $this->getEntityManager()
            ->createQuery(
                'UPDATE AppBundle:offer o SET o.updateDate = CURRENT_TIMESTAMP() WHERE o.employer = '
                .$employerId.' AND o.startDate < CURRENT_TIMESTAMP() AND o.endDate > CURRENT_TIMESTAMP()'
            )->execute();
    }

    public function getNotificationOffers($notification)
    {
        $query = $this->createQueryBuilder('o');
        $query->andWhere('o.startDate > :date OR (o.creationDate > :date AND o.slot is not null)')
            ->setParameter('date', $notification->getDate());

        if($notification->getTypeNotification() == 'employer'){
            $query->andWhere('o.employer = :employer')
            ->setParameter('employer', $notification->getElementId());
        }elseif ($notification->getTypeNotification() == 'tag'){
            $query->andWhere(':tag MEMBER OF o.tag')
            ->setParameter('tag', $notification->getElementId());
        }

        $offers = $query->getQuery()->getResult();

        return $offers;
    }
}
