<?php

namespace AppBundle\Repository;

/**
 * PostulatedOffersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostulatedOffersRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRecentPostulatedOffers($candidate)
    {
        $query = $this->createQueryBuilder('po');
        $query->andWhere('po.archived = 0 and po.date > :date and po.candidate = :candidate')
            ->setParameter('date', new \DateTime('-3 month'))
            ->setParameter('candidate', $candidate);

        $offers = $query->getQuery()->getResult();

        return $offers;
    }

    public function countTotalBefore($date){
        return $this->getEntityManager()
            ->createQuery(
                'select count(distinct po.id) as total
                    from AppBundle:postulatedOffers po
                    where po.date <= :date'
            )->setParameter('date',$date)->execute();
    }

    public function countTotalMonthly($month, $year){
        return $this->getEntityManager()
            ->createQuery(
                'select count(distinct po.id) as total
                    from AppBundle:postulatedOffers po
                    where month(po.date) = :month and year(po.date) = :year'
            )->setParameter('month',$month)->setParameter('year',$year)->execute();
    }

}
