<?php

namespace AppBundle\Repository;

/**
 * PostulatedOffersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostulatedOffersRepository extends \Doctrine\ORM\EntityRepository
{
}
