<?php

namespace AppBundle\Repository;

/**
 * ProRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProRepository extends \Doctrine\ORM\EntityRepository
{
    public function countTotalDifferentPro()
    {
        $query = $this->createQueryBuilder('e')->select("e")
            ->leftJoin('AppBundle:user', 'u', 'WITH', 'e = u.employer');
        $query->andWhere('u.main = 1');

        $employers = $query->getQuery()->getResult();

        return count($employers);
    }

    public function countActiveBetween($endDate){
        return $this->getEntityManager()
            ->createQuery(
                'select count(distinct em.id) as total
                    from AppBundle:employer em
                    where em.creationDate <= :endDate'
            )->setParameter('endDate',$endDate)->execute();
    }
}
