<?php

namespace AppBundle\Repository;

/**
 * RendezvousRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RendezvousRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNext($givenUser){
        return $this->getEntityManager()
            ->createQuery(
                'select r
                    from AppBundle:rendezvous r
                    where r.endDate >= :now and r.user = :user'
            )->setParameter('user',$givenUser)->setParameter('now', new \DateTime())->execute();
    }
}
