<?php

namespace AppBundle\Repository;

/**
 * SlotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlotRepository extends \Doctrine\ORM\EntityRepository
{

    public function getCurrentSlotEmployer($employerId)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s FROM AppBundle:slot s WHERE s.employer = '.$employerId.' AND  s.startDate <= CURRENT_TIMESTAMP() AND s.endDate > CURRENT_TIMESTAMP()'
            )->execute();
    }

    public function countTotalActiveSlot()
    {
        $query = $this->createQueryBuilder('s');
        $query->andWhere('s.startDate <= CURRENT_TIMESTAMP() and s.endDate >= CURRENT_TIMESTAMP()');

        $offers = $query->getQuery()->getResult();

        return count($offers);
    }
}
