create_pro:
    locales:
        en: "/register"
        fr: "/inscription"
    defaults: { _controller: ProBundle:Pro:create }
edit_pro:
    locales:
        en: "/edit"
        fr: "/editer"
    defaults: { _controller: ProBundle:Pro:edit }
delete_pro:
    locales:
        en: "/delete/{id}"
        fr: "/supprimer/{id}"
    defaults: { _controller: ProBundle:Pro:delete }

show_pro:
    locales:
        en: "/{id}"
        fr: "/{id}"
    defaults: { _controller: ProBundle:Pro:show }
    requirements:
        id: \d+
list_pro:
    locales:
        en: "/list-pro"
        fr: "/liste-employeur"
    defaults: { _controller: ProBundle:Pro:list }
dashboard_pro:
    locales:
        en: "/dashboard"
        fr: "/tableaux-de-bord"
    defaults: { _controller: ProBundle:Pro:dashboard}
pro_offers:
    locales:
        en: "/my-offers/{archived}"
        fr: "/mes-offres/{archived}"
    defaults: { _controller: ProBundle:Pro:myOfferPage , archived: 0}
    requirements:
      archived: 0|1
delete_image:
    locales:
        en: "/delete-image"
        fr: "/effacer-image"
    defaults: { _controller: ProBundle:Pro:deleteImage }
post_offer:
    locales:
        en: "/post-offer"
        fr: "/creation-offre"
    defaults: { _controller: ProBundle:Offer:post }
edit_offer:
    locales:
        en: "/edit-offer/{id}"
        fr: "/edition-offre/{id}"
    defaults: { _controller: ProBundle:Offer:edit }
    requirements:
      id: \d+
delete_offer:
    locales:
        en: "/delete-offer"
        fr: "/supprimer-offre"
    defaults: { _controller: ProBundle:Offer:delete }
    requirements:
      id: \d+
erase_offer:
    locales:
        en: "/erase-offer"
        fr: "/effacer-offre"
    defaults: { _controller: ProBundle:Offer:erase }
    requirements:
      id: \d+
activate_offer:
    locales:
        en: "/activate-offer"
        fr: "/activer-offre"
    defaults: { _controller: ProBundle:Offer:activate }
    requirements:
      id: \d+
show_offer:
    locales:
        en: "/Job/{url}/{id}"
        fr: "/Emploi/{url}/{id}"
    defaults: { _controller: ProBundle:Offer:show }
    requirements:
        url:    .*
apply_offer:
    locales:
        en: "/apply-offer/{id}"
        fr: "/postuler-offre/{id}"
    defaults: { _controller: ProBundle:Offer:apply }
    requirements:
      id: \d+
search_offer:
    locales:
        en: "/search-offer"
        fr: "/chercher-offre"
    defaults: { _controller: ProBundle:Pro:search }
search_page_offer:
    locales:
        en: "/search-offer-page"
        fr: "/page-chercher-offre"
    defaults: { _controller: ProBundle:Pro:searchPage }
boost_offers:
    locales:
        en: "/boost-offer"
        fr: "/booster-offre"
    defaults: { _controller: ProBundle:Offer:boost }
increment_offer:
    locales:
        en: "/increment-offer"
        fr: "/incrementer-offre"
    defaults: { _controller: ProBundle:Offer:increment }
featured_pro_page:
    locales:
        en: "/featured-pro"
        fr: "/employeur-en-avant"
    defaults: { _controller: ProBundle:Pro:featuredProPage }
reserve_featured_pro:
    locales:
        en: "/reserve-featured-pro"
        fr: "/reserver-employeur-en-avant"
    defaults: { _controller: ProBundle:Pro:reserveFeaturedPro }
delete_featured_pro:
    locales:
        en: "/delete-featured-pro"
        fr: "/supprimer-employeur-en-avant"
    defaults: { _controller: ProBundle:Pro:deleteFeaturedPro }
featured_offer_page:
    locales:
        en: "/featured-offer"
        fr: "/offre-en-avant"
    defaults: { _controller: ProBundle:Pro:featuredOfferPage }
reserve_featured_offer:
    locales:
        en: "/reserve-featured-offer"
        fr: "/reserver-offre-en-avant"
    defaults: { _controller: ProBundle:Pro:reserveFeaturedOffer }
delete_featured_offer:
    locales:
        en: "/delete-featured-offer"
        fr: "/supprimer-offre-en-avant"
    defaults: { _controller: ProBundle:Pro:deleteFeaturedOffer }
buy_slot:
    locales:
        en: "/buy-slot"
        fr: "/acheter-slot"
    defaults: { _controller: ProBundle:Pro:buySlot }
add_to_slot:
    locales:
        en: "/add-to-slot"
        fr: "/ajouter-aux-slot"
    defaults: { _controller: ProBundle:Pro:addToSlot }
    requirements:
      id: \d+
remove_from_slot:
    locales:
        en: "/remove-from-slot/{id}"
        fr: "/enlever-du-slot/{id}"
    defaults: { _controller: ProBundle:Pro:removeFromSlot }
    requirements:
      id: \d+
empty_slot:
    locales:
        en: "/empty-slot/{id}"
        fr: "/vider-slot/{id}"
    defaults: { _controller: ProBundle:Pro:EmptySlot }
    requirements:
      id: \d+
offer_archived:
    locales:
        en: "/offer-archived/{id}"
        fr: "/offre-archivé/{id}"
    defaults: { _controller: ProBundle:Offer:offerNotFound }
applied_candidate_page:
    locales:
        en: "/candidates-for-offer/{id}"
        fr: "/candidats-a-offre/{id}"
    defaults: { _controller: ProBundle:Pro:listAppliedClientPage }
apply_spontaneous:
    locales:
        en: "/spontaneous-application/{id}"
        fr: "/candidature-spontane/{id}"
    defaults: { _controller: ProBundle:Pro:spontaneousApply }
end_activation_offer_mail:
    locales:
        en: "/mail-end-activation/{days}"
        fr: "/mail-fin-activation/{days}"
    defaults: { _controller: ProBundle:Offer:sendEndActivation }
add_collaborator:
    locales:
        en: "/add-collaborator"
        fr: "/ajout-collaborateur"
    defaults: { _controller: ProBundle:Pro:addCollaborator }
list_collaborator:
    locales:
        en: "/collaborator-list/{id}"
        fr: "/liste-collaborateur/{id}"
    defaults: { _controller: ProBundle:Pro:listCollaborator }
archive_collaborator:
    locales:
        en: "/archive-collaborator/{id}"
        fr: "/archiver-collaborateur/{id}"
    defaults: { _controller: ProBundle:Pro:archiveCollaborator }
change_access_collaborator:
    locales:
        en: "/change-access-collaborator/{id}"
        fr: "/changer-acces-collaborateur/{id}"
    defaults: { _controller: ProBundle:Pro:changeAccessCollaborator }
manage_service:
    locales:
        en: "/manage-service"
        fr: "/gerer-service"
    defaults: { _controller: ProBundle:Service:manageService }
manage_schedule:
    locales:
        en: "/manage-schedule"
        fr: "/gerer-emplois-du-temps"
    defaults: { _controller: ProBundle:Service:manageSchedule }
save_schedule:
    locales:
        en: "/save-schedule"
        fr: "/sauver-emplois-du-temps"
    defaults: { _controller: ProBundle:Service:saveSchedule }
remove_schedule:
    locales:
        en: "/remove-schedule"
        fr: "/enlever-emplois-du-temps"
    defaults: { _controller: ProBundle:Service:removeSchedule }
replicate_schedule:
    locales:
        en: "/replicate-schedule"
        fr: "/repliquer-emplois-du-temps"
    defaults: { _controller: ProBundle:Service:replicateSchedule }
reservation_page:
    locales:
        en: "/reservation-page"
        fr: "/page-de-reservation"
    defaults: { _controller: ProBundle:Service:reservationPage }
reserve_rendezvous:
    locales:
        en: "/reserve"
        fr: "/reserver"
    defaults: { _controller: ProBundle:Service:reserve }
rendezvous_page:
    locales:
        en: "/rendezvous-page"
        fr: "/page-rendezvous"
    defaults: { _controller: ProBundle:Service:rendezvousPage }
cancel_rendezvous:
    locales:
        en: "/cancel-rendezvous"
        fr: "/annuler-rendezvous"
    defaults: { _controller: ProBundle:Service:cancelRendezvous }
manage_general_schedule:
    locales:
        en: "/manage-general-schedule"
        fr: "/modifier-horaire-globale"
    defaults: { _controller: ProBundle:Service:manageGeneralSchedule }

send_reminder:
    locales:
        en: "/send-reminder"
        fr: "/envoyer-rappel"
    defaults: { _controller: ProBundle:Service:sendReminder }